apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: exporter
    name: exporter
  spec:
    replicas: 1
    selector:
      app: exporter
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: exporter
      spec:
        containers:
        - args:
          - -haproxy.scrape-uri=http://$(USERNAME):${PASSWORD}@router/haproxy?stats;csv
          image: prom/haproxy-exporter
          imagePullPolicy: Always
          name: exporter
          ports:
          - containerPort: 9101
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: haproxy-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: haproxy-secret
                  key: password
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: exporter
    name: exporter
  spec:
    ports:
    - port: 9101
      protocol: TCP
      targetPort: 9101
    selector:
      app: exporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
